<?php

/**
 * Implements hook_permission().
 * Set Permission Definitions.
 */
function writer_permission() {
    $permissions = array(
        'edit_writer_settings' => array(
            'title' => t("Edit writer settings"),
        ),
    );
}

/**
 * Implements hook_menu().
 * Creates menu items and routes.
 */
function writer_menu() {
    $menu_items = array();

    $menu_items['writer/test'] = array(
        'title' => t("test route"),
        'page callback' => 'writer_test_route',
        'access arguments' => array('edit_writer_settings')
    );

    return $menu_items;
}

function writer_test_route() {
    $html = "<h2>Hello Test</h2>";
    return $html;
}

/**
 * Implements hook_field_widget_info().
 */
function writer_field_widget_info() {
    return array(
        'writer_block_widget' => array(
          'label' => t("Writer's block"),
          'field types' => array('text_long'),
        ),
      );
}

/**
 * Implements hook_field_widget_form().
 */
function writer_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
    $value = isset($items[$delta]['value']) ? $items[$delta]['value'] : '';
    $widget = $element;
    $widget['#delta'] = $delta;

    switch ($instance['widget']['type']) {

        case 'writer_block_widget':
        $widget += array(
            '#type' => 'textarea',
            '#prefix' => "<div id='writer-block'>",
            '#suffix' => "</div>",
            '#default_value' => $value,
            );
          break;
      }
    
      $element['value'] = $widget;
      return $element;    
}
