<?php

/**
 * Implements hook_permission().
 * Set Permission Definitions.
 */
function writer_permission() {
    $permissions = array(
        'edit_writer_settings' => array(
            'title' => t("Edit writer settings"),
        ),
    );
}

/**
 * Implements hook_field_widget_info().
 */
function writer_field_widget_info() {
    return array(
        'writer_block_widget' => array(
          'label' => t("Writer's block"),
          'field types' => array('text_long'),
        ),
      );
}

/**
 * Implements hook_field_widget_form().
 */
function writer_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
    $value = isset($items[$delta]['value']) ? $items[$delta]['value'] : '';
    $widget = $element;
    $widget['#delta'] = $delta;

    switch ($instance['widget']['type']) {

        case 'writer_block_widget':
            $widget += array(
                '#type' => 'textarea',
                '#default_value' => $value,
                '#attributes' => array('id' => array('writer-block')),
                '#attached' => array(
                    'js' => array(
                        'data' => backdrop_get_path('module', 'writer') . '/js/build/app.bundle.js',
                        'group' => JS_DEFAULT,
                        'every_page' => FALSE,
                        'type' => 'file',
                        'preprocess' => FALSE,
                        'scope' => 'footer',
                    ),
                ),
            );
            break;
      }
    
      $element['value'] = $widget;
      return $element;    
}
