<?php

/**
 * Implements hook_permission().
 * Set Permission Definitions.
 */
function writer_permission() {
    $permissions = array(
        'edit_writer_settings' => array(
            'title' => t("Edit writer settings"),
        ),
    );
}

/**
 * Implements hook_field_widget_info().
 */
function writer_field_widget_info() {
    return array(
        'writer_block_widget' => array(
          'label' => t("Writer's block"),
          'field types' => array('text_long'),
        ),
      );
}

/**
 * Implements hook_field_widget_form().
 */
function writer_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
    $value = isset($items[$delta]['value']) ? $items[$delta]['value'] : '';
    $widget = $element;
    $widget['#delta'] = $delta;

    switch ($instance['widget']['type']) {

        case 'writer_block_widget':
            // Allow React access to default field value
            backdrop_add_js(array('writer'=>array("textfield" => $value)), 'setting');
            $element['#attached']['js'][] = array(
                'type'      => 'file',
                'data'      => backdrop_get_path('module', 'writer') . '/js/build/app.bundle.js',
                'scope'     => 'footer',
                'weight'    => 5,
              );
            $element['#prefix'] = '<div id="writer-block">';
            $element['#suffix'] = '</div>';

            $element['#type'] = 'textarea';
            // $element['#attributes'] = array('id' => array('writer-block'));
            $widget = $element;
            break;
      }
    
      $element['value'] = $widget;
      return $element;    
}
